name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.0"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Start server
        run: npm run dev &
        env:
          VITE_APP_PORT: 4000
          CI: true

      - name: Wait for server to be up
        run: npx wait-on http://localhost:4000

      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          VITE_APP_PORT: 4000
